[openai]
api_key = "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"  # your OpenAI key here
model = "gpt-4-0125-preview"

[unsplash]
api_key = "SxJLc9lqQbIqdh7rIRtDtqfSuXRJ5fVYZrkbB8_xx5I"