[openai]
api_key = "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"
model = "gpt-4-0125-preview"

[unsplash]
api_key = "SxJLc9lqQbIqdh7rIRtDtqfSuXRJ5fVYZrkbB8_xx5I"

[locationiq]
api_key = "pk.72f858045f84e35da25e115d54a59515"